version: '3'
services:
  challenge:
    build: distfiles/service
    ports:
      - "8888:8080"
    links:
      - redis
    environment:
      - UWSGI_INI=/app/uwsgi.ini
      - LISTEN_PORT=8080
      - FLAG="CakeCTF{b3_c4ut10us_1f_s3ss10n_1s_cl13nt_s1d3_0r_s3rv3r_s1d3}"
    restart: unless-stopped

  redis:
    build: distfiles/redis
    restart: unless-stopped
